### ISSUE TITLE
See my recent activity opens backoffice vision

### ISSUE THREAD

**Issue by lmfduarte** [PrimaveraDeveloper/identity-server#1]
With a new user without backoffice access:
Click at 'More' in 'Your recent activity'
In any row click at 'View'
At this moment show backffice view

![image](https://user-images.githubusercontent.com/61735296/113861887-a512d080-979f-11eb-8f8c-2a09c8247053.png)

**Comment by hugoqribeiro** [comment]
@lmfduarte fixed in 05.00.00.0053
