### ISSUE TITLE
Add secret to client credentials client doesn't work

### ISSUE THREAD

**Issue by lmfduarte** [PrimaveraDeveloper/identity-server#2]
Create a new client, in this case, lithium-digitalarchiveservice-admin-clientcredentials
In grant types choose 'client_credentials'
Add some scopes
Go to tab 'Secrets' and click on 'Add'
Nothing happens and in chrome console, this message appears:

![image](https://user-images.githubusercontent.com/61735296/113891483-05fcd180-97bd-11eb-99ee-b2d64f128108.png)

**Comment by hugoqribeiro** [comment]
@lmfduarte fixed in 05.00.00.0053
